version: "3.8"
services:
  db:
    image: postgres:14
    container_name: nest_postgres
    ports:
      - 5434:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nest_db
      - POSTGRES_PASSWORD=password
    networks:
      - default_network
volumes:
  db-store:
networks:
  default_network:
